name: Deploy on Private Zero Tier Docker Machine

on:
  workflow_call:
    inputs:
      command:
        description: "Command to execute on host"
        type: string
        required: true
    secrets:
      HOST:
        required: true
      PORT:
        required: true
      PASSWORD:
        required: true
      USERNAME:
        required: true
      ZEROTIER_NETWORK_ID:
        required: true
      ZEROTIER_API_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ZeroTier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_API_TOKEN }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: ${{ inputs.command }}

      - name: Remove ZeroTier node from network
        if: always()
        env:
          ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
          ZEROTIER_API_TOKEN: ${{ secrets.ZEROTIER_API_TOKEN }}
        run: |
          # Remover o nó da rede ZeroTier usando a API
          curl -X DELETE "https://api.zerotier.com/api/v1/network/$ZEROTIER_NETWORK_ID/member/$ZEROTIER_NODE_ID" \
            -H "Authorization: Bearer $ZEROTIER_API_TOKEN"

          echo "ZeroTier node removido com sucesso da rede"
